#!/bin/bash
#for C tags
ctags -I __THROW -I __nonnull -I __THROWNL -I __wur -I __attribute_malloc__ --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c-kinds=+p --fields=+iaS --extra=+q -R -f ~/.vim/systags /usr/include

#for stdC++ tags
ctags -R --sort=1 --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ -f ~/.vim/cpptags ~/.vim/cpp_src

